// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Filter options for querying beans
type BeanFilter struct {
	// Full-text search across slug, title, and body using Bleve query syntax.
	//
	// Examples:
	// - "login" - exact term match
	// - "login~" - fuzzy match (1 edit distance)
	// - "login~2" - fuzzy match (2 edit distance)
	// - "log*" - wildcard prefix
	// - "\"user login\"" - exact phrase
	// - "user AND login" - both terms required
	// - "user OR login" - either term
	// - "slug:auth" - search only slug field
	// - "title:login" - search only title field
	// - "body:auth" - search only body field
	Search *string `json:"search,omitempty"`
	// Include only beans with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude beans with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only beans with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude beans with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only beans with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude beans with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only beans with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude beans with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Include only beans with a parent
	HasParent *bool `json:"hasParent,omitempty"`
	// Include only beans with this specific parent ID
	ParentID *string `json:"parentId,omitempty"`
	// Include only beans that are blocking other beans
	HasBlocking *bool `json:"hasBlocking,omitempty"`
	// Include only beans that are blocking this specific bean ID
	BlockingID *string `json:"blockingId,omitempty"`
	// Include only beans that are blocked by others (via incoming blocking links or blocked_by field)
	IsBlocked *bool `json:"isBlocked,omitempty"`
	// Include only beans that have explicit blocked-by entries
	HasBlockedBy *bool `json:"hasBlockedBy,omitempty"`
	// Include only beans blocked by this specific bean ID (via blocked_by field)
	BlockedByID *string `json:"blockedById,omitempty"`
	// Exclude beans that have a parent
	NoParent *bool `json:"noParent,omitempty"`
	// Exclude beans that are blocking other beans
	NoBlocking *bool `json:"noBlocking,omitempty"`
	// Exclude beans that have explicit blocked-by entries
	NoBlockedBy *bool `json:"noBlockedBy,omitempty"`
	// Include archived beans in results (default: false)
	IncludeArchived *bool `json:"includeArchived,omitempty"`
}

// Structured body modifications applied atomically.
// Operations are applied in order: all replacements sequentially, then append.
// If any operation fails, the entire mutation fails (transactional).
type BodyModification struct {
	// Text replacements applied sequentially in array order.
	// Each old text must match exactly once at the time it's applied.
	Replace []*ReplaceOperation `json:"replace,omitempty"`
	// Text to append after all replacements.
	// Appended with blank line separator.
	Append *string `json:"append,omitempty"`
}

// Input for creating a new bean
type CreateBeanInput struct {
	// Bean title (required)
	Title string `json:"title"`
	// Bean type (defaults to 'task')
	Type *string `json:"type,omitempty"`
	// Status (defaults to 'todo')
	Status *string `json:"status,omitempty"`
	// Priority level (defaults to 'normal')
	Priority *string `json:"priority,omitempty"`
	// Tags for categorization
	Tags []string `json:"tags,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
	// Parent bean ID (validated against type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Bean IDs this bean is blocking
	Blocking []string `json:"blocking,omitempty"`
	// Bean IDs that are blocking this bean
	BlockedBy []string `json:"blockedBy,omitempty"`
	// Custom ID prefix (overrides config prefix for this bean)
	Prefix *string `json:"prefix,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// A single text replacement operation.
type ReplaceOperation struct {
	// Text to find (must occur exactly once, cannot be empty)
	Old string `json:"old"`
	// Replacement text (can be empty to delete the matched text)
	New string `json:"new"`
}

// Input for updating an existing bean
type UpdateBeanInput struct {
	// New title
	Title *string `json:"title,omitempty"`
	// New status
	Status *string `json:"status,omitempty"`
	// New type
	Type *string `json:"type,omitempty"`
	// New priority
	Priority *string `json:"priority,omitempty"`
	// Replace all tags (nil preserves existing, mutually exclusive with addTags/removeTags)
	Tags []string `json:"tags,omitempty"`
	// Add tags to existing list
	AddTags []string `json:"addTags,omitempty"`
	// Remove tags from existing list
	RemoveTags []string `json:"removeTags,omitempty"`
	// New body content (full replacement, mutually exclusive with bodyMod)
	Body *string `json:"body,omitempty"`
	// Structured body modifications (mutually exclusive with body)
	BodyMod *BodyModification `json:"bodyMod,omitempty"`
	// Set parent bean ID (null/empty to clear, validates type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Add beans to blocking list (validates cycles and existence)
	AddBlocking []string `json:"addBlocking,omitempty"`
	// Remove beans from blocking list
	RemoveBlocking []string `json:"removeBlocking,omitempty"`
	// Add beans to blocked-by list (validates cycles and existence)
	AddBlockedBy []string `json:"addBlockedBy,omitempty"`
	// Remove beans from blocked-by list
	RemoveBlockedBy []string `json:"removeBlockedBy,omitempty"`
	// ETag for optimistic concurrency control (optional)
	IfMatch *string `json:"ifMatch,omitempty"`
}
